apiVersion: v1
kind: Service
metadat:
    name: db
    labels:
        name: db-service
        app: demo-voting-app
specs:
    ports:
    - port: 5432
      targetPort: 5432
    selector:
        name: postgres-pod
        app: demo-voting-app